---
- name: services | Ensuring Guacamole Server Service Is Enabled And Starts On Boot
  ansible.builtin.service:
    name: guacd
    enabled: true
    state: started
  become: true
  when: guacd_config.install
