---
- name: set_facts | Setting Debian/Ubuntu Facts
  ansible.builtin.set_fact:
    guacamole_freerdp: freerdp-x11
    guacamole_freerdp_dev: libfreerdp-dev
    guacamole_tomcat: tomcat7
    guacamole_tomcat_service: tomcat7
    guacamole_tomcat_user: tomcat7
  when: >
    (ansible_distribution == "Debian" and
    ansible_distribution_version is version('9', '<')) or
    (ansible_distribution == "Ubuntu" and
    ansible_distribution_version is version('18.04', '<'))

- name: set_facts | Setting Debian/Ubuntu Facts
  ansible.builtin.set_fact:
    guacamole_freerdp: freerdp-x11
    guacamole_freerdp_dev: freerdp2-dev
    guacamole_tomcat: tomcat8
    guacamole_tomcat_service: tomcat8
    guacamole_tomcat_user: tomcat8
  when: >
    (ansible_distribution == "Debian" and
    ansible_distribution_version is version('9', '==')) or
    (ansible_distribution == "Ubuntu" and
    ansible_distribution_version is version('18.04', '>=') and
    ansible_distribution_version is version('19.10', '<='))

- name: set_facts | Setting Debian/Ubuntu Facts
  ansible.builtin.set_fact:
    guacamole_freerdp: freerdp2-x11
    guacamole_freerdp_dev: freerdp2-dev
    guacamole_tomcat: tomcat9
    guacamole_tomcat_service: tomcat9
    guacamole_tomcat_user: tomcat
  when: >
    (ansible_distribution == "Debian" and
    ansible_distribution_version is version('9', '>')) or
    (ansible_distribution == "Ubuntu" and
    ansible_distribution_version is version('19.10', '>='))

- name: set_facts | Setting RedHat Facts
  ansible.builtin.set_fact:
    guacamole_tomcat: tomcat
    guacamole_tomcat_service: tomcat
    guacamole_tomcat_user: tomcat
  when:
    - ansible_os_family == "RedHat"

- name: set_facts | Setting Debian Packages
  ansible.builtin.set_fact:
    guacamole_debian_pre_reqs:
      - "{{ guacamole_tomcat }}"
      - build-essential
      - "{{ guacamole_freerdp }}"
      - libavcodec-dev
      - libavutil-dev
      - libcairo2-dev
      - "{{ guacamole_freerdp_dev }}"
      - libjpeg62-turbo-dev
      - libossp-uuid-dev
      - libpango1.0-dev
      - libpng12-dev
      - libpulse-dev
      - libssh2-1-dev
      - libssl-dev
      - libswscale-dev
      - libtelnet-dev
      - libvncserver-dev
      - libvorbis-dev
      - libwebp-dev
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version is version('9', '<')

- name: set_facts | Setting Debian Packages
  ansible.builtin.set_fact:
    guacamole_debian_pre_reqs:
      - "{{ guacamole_tomcat }}"
      - build-essential
      - "{{ guacamole_freerdp }}"
      - libavcodec-dev
      - libavutil-dev
      - libcairo2-dev
      - "{{ guacamole_freerdp_dev }}"
      - libjpeg62-turbo-dev
      - libossp-uuid-dev
      - libpango1.0-dev
      - libpng-dev
      - libpulse-dev
      - libssh2-1-dev
      - libssl-dev
      - libswscale-dev
      - libtelnet-dev
      - libvncserver-dev
      - libvorbis-dev
      - libwebp-dev
      - libwebsockets-dev
      - libavformat-dev
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version is version('9', '>=')

- name: set_facts | Setting Ubuntu Packages
  ansible.builtin.set_fact:
    guacamole_debian_pre_reqs:
      - "{{ guacamole_tomcat }}"
      - build-essential
      - dpkg-dev
      - "{{ guacamole_freerdp }}"
      - ghostscript
      - libavcodec-dev
      - libavutil-dev
      - libcairo2-dev
      - "{{ guacamole_freerdp_dev }}"
      - libjpeg-turbo8-dev
      - libossp-uuid-dev
      - libpango1.0-dev
      - libpng12-dev
      - libpulse-dev
      - libssh2-1-dev
      - libssl-dev
      - libswscale-dev
      - libtelnet-dev
      - libvncserver-dev
      - libvorbis-dev
      - libwebp-dev
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('18.04', '<')

- name: set_facts | Setting Ubuntu Packages
  ansible.builtin.set_fact:
    guacamole_debian_pre_reqs:
      - "{{ guacamole_tomcat }}"
      - build-essential
      - "{{ guacamole_freerdp }}"
      - libavcodec-dev
      - libavutil-dev
      - libcairo2-dev
      - "{{ guacamole_freerdp_dev }}"
      - libjpeg-turbo8-dev
      - libossp-uuid-dev
      - libpango1.0-dev
      - libpng-dev
      - libpulse-dev
      - libssh2-1-dev
      - libssl-dev
      - libswscale-dev
      - libtelnet-dev
      - libvncserver-dev
      - libvorbis-dev
      - libwebp-dev
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('18.04', '>=')

- name: set_facts | Setting RedHat Packages
  ansible.builtin.set_fact:
    guacamole_redhat_pre_reqs:
      - "{{ guacamole_tomcat }}"
      - cairo-devel
      - ffmpeg-devel
      - freerdp-devel
      - gcc
      - libjpeg-turbo-devel
      - libpng-devel
      - libssh2-devel
      - libtelnet-devel
      - libvncserver-devel
      - libvorbis-devel
      - libwebp-devel
      - make
      # - maven
      - openssl-devel
      - pango-devel
      - pulseaudio-libs-devel
      - uuid-devel
  when:
    - ansible_os_family == "RedHat"

- name: set_facts | Fix guacamole 1.5.4 compile issue
  ansible.builtin.set_fact:
    guacamole_compile_environment:
      LDFLAGS: '-lrt'
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version is version('9', '>=')
    - guacamole_version == "1.5.4"
