---
# handlers file for ansible-guacamole
- name: kill guacd # noqa no-changed-when
  ansible.builtin.command: pkill guacd
  become: true
  when: guacd_config.install

- name: restart guacd
  ansible.builtin.service:
    name: guacd
    state: restarted
  become: true
  when: guacd_config.install

- name: restart tomcat
  ansible.builtin.service:
    name: tomcat
    state: restarted
  become: true

- name: restart tomcat7
  ansible.builtin.service:
    name: tomcat7
    state: restarted
  become: true

- name: restart tomcat8
  ansible.builtin.service:
    name: tomcat8
    state: restarted
  become: true

- name: restart tomcat9
  ansible.builtin.service:
    name: tomcat9
    state: restarted
  become: true
